# Generated by Django 5.1.2 on 2026-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GnbConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gnb_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('freq_mhz', models.FloatField()),
                ('power_dbm', models.FloatField()),
                ('bw_hz', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('gnb_created_at', models.DateTimeField(auto_now_add=True)),
                ('gnb_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gnb_config',
            },
        ),
        migrations.CreateModel(
            name='GnbState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('position_json', models.JSONField()),
                ('state_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gnb_state',
            },
        ),
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('payload_json', models.JSONField()),
                ('event_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'platform_events',
            },
        ),
        migrations.CreateModel(
            name='SceneSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scene_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('scene_id', models.CharField(db_index=True, max_length=128)),
                ('config_json', models.JSONField()),
                ('scene_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scene_snapshot',
            },
        ),
        migrations.CreateModel(
            name='UeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ue_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('waypoints_json', models.JSONField(default=list)),
                ('speed_mps', models.FloatField(default=1.0)),
                ('loop', models.BooleanField(default=True)),
                ('ue_created_at', models.DateTimeField(auto_now_add=True)),
                ('ue_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ue_config',
            },
        ),
        migrations.CreateModel(
            name='UeState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('position_json', models.JSONField(default=dict)),
                ('serving_cell', models.CharField(blank=True, max_length=128, null=True)),
                ('rsrp_dbm', models.FloatField(blank=True, null=True)),
                ('sinr_db', models.FloatField(blank=True, null=True)),
                ('state_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ue_state',
            },
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(max_length=16)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('position_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'position_history',
                'indexes': [models.Index(fields=['entity_name', 'position_ts'], name='ix_posh_entity_ts')],
            },
        ),
        migrations.CreateModel(
            name='SignalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signal_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ue_name', models.CharField(db_index=True, max_length=128)),
                ('serving_cell', models.CharField(max_length=128)),
                ('rsrp_dbm', models.FloatField()),
                ('sinr_db', models.FloatField()),
                ('rsrp_map_json', models.JSONField(default=dict)),
                ('signal_ts', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'signal_history',
                'indexes': [models.Index(fields=['ue_name', 'signal_ts'], name='ix_sigh_ue_ts')],
            },
        ),
    ]
