# Generated by Django 5.1.2 on 2026-04-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('scene_id', models.CharField(blank=True, default='', max_length=128)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('pos_z', models.FloatField(default=0)),
                ('size_x', models.FloatField(default=10)),
                ('size_y', models.FloatField(default=10)),
                ('size_z', models.FloatField(default=10)),
                ('color_r', models.FloatField(default=0.75)),
                ('color_g', models.FloatField(default=0.75)),
                ('color_b', models.FloatField(default=0.75)),
                ('usd_path', models.CharField(blank=True, default='', max_length=512)),
                ('target_height_m', models.FloatField(blank=True, null=True)),
                ('rot_x', models.FloatField(default=0)),
                ('rot_y', models.FloatField(default=0)),
                ('rot_z', models.FloatField(default=0)),
                ('material', models.CharField(blank=True, default='', max_length=128)),
                ('building_created_at', models.DateTimeField(auto_now_add=True)),
                ('building_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'building_object',
            },
        ),
        migrations.CreateModel(
            name='ObstacleObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obstacle_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('scene_id', models.CharField(blank=True, default='', max_length=128)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('pos_z', models.FloatField(default=0)),
                ('size_x', models.FloatField(default=10)),
                ('size_y', models.FloatField(default=10)),
                ('size_z', models.FloatField(default=10)),
                ('color_r', models.FloatField(default=0.75)),
                ('color_g', models.FloatField(default=0.75)),
                ('color_b', models.FloatField(default=0.75)),
                ('material', models.CharField(blank=True, default='', max_length=128)),
                ('usd_path', models.CharField(blank=True, default='', max_length=512)),
                ('scale_x', models.FloatField(default=1.0)),
                ('scale_y', models.FloatField(default=1.0)),
                ('scale_z', models.FloatField(default=1.0)),
                ('obstacle_created_at', models.DateTimeField(auto_now_add=True)),
                ('obstacle_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'obstacle_object',
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('scene_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ended', 'Ended')], db_index=True, default='running', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'simulation_session',
            },
        ),
        migrations.AddField(
            model_name='gnbconfig',
            name='color_b',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gnbconfig',
            name='color_g',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gnbconfig',
            name='color_r',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gnbconfig',
            name='pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gnbconfig',
            name='pos_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gnbconfig',
            name='pos_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gnbconfig',
            name='target_height_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='session_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signalhistory',
            name='session_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ueconfig',
            name='color_b',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='ueconfig',
            name='color_g',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='ueconfig',
            name='color_r',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='ueconfig',
            name='pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ueconfig',
            name='pos_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ueconfig',
            name='pos_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ueconfig',
            name='target_height_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ueconfig',
            name='usd_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddIndex(
            model_name='positionhistory',
            index=models.Index(fields=['session_uuid', 'position_ts'], name='ix_posh_session_ts'),
        ),
        migrations.AddIndex(
            model_name='signalhistory',
            index=models.Index(fields=['session_uuid', 'signal_ts'], name='ix_sigh_session_ts'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['session_uuid'], name='ix_simsession_uuid'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['scene_id', 'created_at'], name='ix_simsession_scene_created'),
        ),
    ]
