# Generated by Django 5.1.2 on 2026-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ran', '0007_add_gnb_cells'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalhistory',
            name='serving_cell_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signalhistory',
            name='serving_gnb',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signalhistory',
            name='serving_pci',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
