# Generated by Django 5.1.2 on 2026-07-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ran', '0015_drop_obstacle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapScene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=256)),
                ('min_lon', models.FloatField()),
                ('min_lat', models.FloatField()),
                ('max_lon', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('usd_path', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('building_count', models.IntegerField(default=0)),
                ('height_max_m', models.FloatField(default=0.0)),
                ('extent_ew_m', models.FloatField(default=0.0)),
                ('extent_ns_m', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map_scene',
                'ordering': ('-created_at',),
            },
        ),
    ]
