# Generated by Django 5.1.2 on 2026-07-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ran', '0016_mapscene'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapscene',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
